"""
Django settings for webcup2026 project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:  # pragma: no cover — PyMySQL is a declared dependency
    pymysql = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = BASE_DIR / 'templates'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b&3kevr@+jhaq)ct(8$5zap)&4rpm(-sd9o30wuouag_8#&mm5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','https://technophile.rodrigues.webcup.hodi.cloud/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'terra',
    'pwa',
    'pwa_webpush',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this line
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webcup2026.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'terra.context_processors.notifications',
                'terra.context_processors.net_tier',
                'terra.context_processors.webpush',
                'terra.context_processors.tutorial',
            ],
        },
    },
]

WSGI_APPLICATION = 'webcup2026.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Production (Hodifly) runs on MySQL via PyMySQL. If the server can't be
# reached with these credentials, we fall back to the local SQLite file so the
# site never hard-fails on a bad database connection.

_MYSQL = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'technophile_webcup',
    'USER': 'technophile_marius',
    'PASSWORD': 'webcup2026',
    'HOST': 'localhost',
    'PORT': '3306',
    'OPTIONS': {'charset': 'utf8mb4'},
}

_SQLITE = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}


def _mysql_reachable():
    """True when the MySQL server accepts a connection with our credentials."""
    if pymysql is None:
        return False
    try:
        conn = pymysql.connect(
            host=_MYSQL['HOST'],
            port=int(_MYSQL['PORT']),
            user=_MYSQL['USER'],
            password=_MYSQL['PASSWORD'],
            database=_MYSQL['NAME'],
            connect_timeout=3,
        )
        conn.close()
        return True
    except Exception:
        return False


if _mysql_reachable():
    DATABASES = {'default': _MYSQL}
else:
    print('MySQL unreachable — falling back to SQLite (db.sqlite3).', file=sys.stderr)
    DATABASES = {'default': _SQLITE}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Sessions
# Store sessions in a signed cookie instead of the database so logins survive
# on Hodifly, whose Passenger releases are immutable — SQLite session rows
# written at request time can be lost before the next request. The session here
# only holds auth identity + flash messages, so a cookie is more than enough.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTPONLY = True

# The site runs over HTTPS behind a proxy that may not forward the scheme, so
# trust its origin for CSRF checks on admin POSTs (logout, actions, edits).
CSRF_TRUSTED_ORIGINS = ['https://technophile.rodrigues.webcup.hodi.cloud']


# Authentication
# https://docs.djangoproject.com/en/6.1/topics/auth/

LOGIN_URL = 'terra:login'
LOGIN_REDIRECT_URL = 'terra:dashboard'
LOGOUT_REDIRECT_URL = 'terra:home'


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('mg', 'Malagasy'),
    ('mfe', 'Morisien'),
    ('zh', '中文'),
    ('ru', 'Русский'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Progressive Web App
# https://github.com/silviolleite/django-pwa

PWA_SERVICE_WORKER_PATH = BASE_DIR / 'serviceworker.js'
PWA_APP_NAME = 'Terra Nova'
PWA_APP_DESCRIPTION = (
    'A second Earth, catalogued and waiting. Claim your passage, '
    'receive your callsign and watch the departure window count down.'
)
PWA_APP_LANG = 'en-us'
PWA_APP_ROOT_URL = '/'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_FETCH_URL = '/'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_ORIENTATION = 'any'
PWA_APP_DIR = 'ltr'
PWA_APP_THEME_COLOR = '#04060b'
PWA_APP_BACKGROUND_COLOR = '#04060b'
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'
PWA_APP_DEBUG_MODE = DEBUG
PWA_APP_SPLASH_SCREEN = []  # our own art direction — no stock splash screens
PWA_APP_ICONS = [
    {
        'src': '/static/img/pwa/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any',
    },
    {
        'src': '/static/img/pwa/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any',
    },
    {
        'src': '/static/img/pwa/maskable-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'maskable',
    },
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/pwa/apple-touch-icon-180x180.png',
        'sizes': '180x180',
        'type': 'image/png',
    },
]
PWA_APP_SHORTCUTS = [
    {
        'name': 'Mission Control',
        'short_name': 'Control',
        'description': 'Your callsign, sector and departure countdown.',
        'url': '/mission-control/',
        'icons': [{'src': '/static/img/pwa/icon-192x192.png', 'sizes': '192x192'}],
    },
    {
        'name': 'Claim passage',
        'short_name': 'Passage',
        'description': 'Join the passenger registry for Expedition 01.',
        'url': '/signup/',
        'icons': [{'src': '/static/img/pwa/icon-192x192.png', 'sizes': '192x192'}],
    },
    {
        'name': 'TerraX market',
        'short_name': 'TerraX',
        'description': 'Live TerraX prices, trading desk and services.',
        'url': '/market/',
        'icons': [{
            'src': '/static/img/terrax/terrax-192.png',
            'sizes': '192x192',
            'type': 'image/png',
        }],
    },
]


# Web Push (django-pwa-webpush) — VAPID keys for the heat-alert push
# service. VAPID_ADMIN_EMAIL becomes the "mailto:" subject the push
# services use to contact the application operator.
WEBPUSH_SETTINGS = {
    'VAPID_PUBLIC_KEY': (
        'BF_NxwUAbgdKlEuVsmLC7xTt2bb_Hde-pCdRm6kkUAaxF0-bokx38ojia-'
        'zdhPiupHKSavwI3DIQmPjN5jjmsB4'
    ),
    'VAPID_PRIVATE_KEY': 'ZOMlLDMy-dXQpOFfxQuwXFObaEIIEElfG-J4Q_p7_9M',
    'VAPID_ADMIN_EMAIL': 'ice.glisik@gmail.com',
}