"""
Django settings for webcup2026 project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = BASE_DIR / 'templates'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b&3kevr@+jhaq)ct(8$5zap)&4rpm(-sd9o30wuouag_8#&mm5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','https://technophile.rodrigues.webcup.hodi.cloud/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'terra',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this line
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webcup2026.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'terra.context_processors.notifications',
                'terra.context_processors.net_tier',
            ],
        },
    },
]

WSGI_APPLICATION = 'webcup2026.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Authentication
# https://docs.djangoproject.com/en/6.1/topics/auth/

LOGIN_URL = 'terra:login'
LOGIN_REDIRECT_URL = 'terra:dashboard'
LOGOUT_REDIRECT_URL = 'terra:home'


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
    ('mg', 'Malagasy'),
    ('mfe', 'Morisien'),
    ('zh', '中文'),
    ('ru', 'Русский'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Progressive Web App
# https://github.com/silviolleite/django-pwa

PWA_SERVICE_WORKER_PATH = BASE_DIR / 'serviceworker.js'
PWA_APP_NAME = 'Terra Nova'
PWA_APP_DESCRIPTION = (
    'A second Earth, catalogued and waiting. Claim your passage, '
    'receive your callsign and watch the departure window count down.'
)
PWA_APP_LANG = 'en-us'
PWA_APP_ROOT_URL = '/'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_FETCH_URL = '/'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_ORIENTATION = 'any'
PWA_APP_DIR = 'ltr'
PWA_APP_THEME_COLOR = '#04060b'
PWA_APP_BACKGROUND_COLOR = '#04060b'
PWA_APP_STATUS_BAR_COLOR = 'black-translucent'
PWA_APP_DEBUG_MODE = DEBUG
PWA_APP_SPLASH_SCREEN = []  # our own art direction — no stock splash screens
PWA_APP_ICONS = [
    {
        'src': '/static/img/pwa/icon-192x192.png',
        'sizes': '192x192',
        'type': 'image/png',
        'purpose': 'any',
    },
    {
        'src': '/static/img/pwa/icon-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'any',
    },
    {
        'src': '/static/img/pwa/maskable-512x512.png',
        'sizes': '512x512',
        'type': 'image/png',
        'purpose': 'maskable',
    },
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/pwa/apple-touch-icon-180x180.png',
        'sizes': '180x180',
        'type': 'image/png',
    },
]
PWA_APP_SHORTCUTS = [
    {
        'name': 'Mission Control',
        'short_name': 'Control',
        'description': 'Your callsign, sector and departure countdown.',
        'url': '/mission-control/',
        'icons': [{'src': '/static/img/pwa/icon-192x192.png', 'sizes': '192x192'}],
    },
    {
        'name': 'Claim passage',
        'short_name': 'Passage',
        'description': 'Join the passenger registry for Expedition 01.',
        'url': '/signup/',
        'icons': [{'src': '/static/img/pwa/icon-192x192.png', 'sizes': '192x192'}],
    },
    {
        'name': 'TerraX market',
        'short_name': 'TerraX',
        'description': 'Live TerraX prices, trading desk and services.',
        'url': '/market/',
        'icons': [{
            'src': '/static/img/terrax/terrax-192.png',
            'sizes': '192x192',
            'type': 'image/png',
        }],
    },
]