# Generated by Django 6.1.1 on 2026-10-03 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(editable=False, max_length=24, unique=True)),
                ('sector', models.CharField(choices=[('aurelia', 'Aurelia Basin'), ('vermilion', 'Vermilion Steps'), ('glasslands', 'The Glass Tundra'), ('pelagos', 'Pelagos Deep')], default='aurelia', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
