# Generated by Django 6.1.1 on 2026-10-03 10:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trx_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='usd_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('service', 'Service')], max_length=10)),
                ('trx', models.DecimalField(decimal_places=6, help_text='Signed TerraX amount (negative = spent).', max_digits=14)),
                ('usd', models.DecimalField(decimal_places=2, help_text='Signed Earth-credit amount (negative = spent).', max_digits=12)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
