# Generated by Django 6.1.1 on 2026-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0003_profile_is_agent_chatthread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('kind', models.CharField(default='heat', max_length=16)),
                ('severity', models.CharField(choices=[('elevated', 'Elevated'), ('high', 'High'), ('extreme', 'Extreme')], max_length=10)),
                ('temp_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('anomaly', models.DecimalField(decimal_places=1, max_digits=4)),
                ('headline', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
