# Generated by Django 6.1.1 on 2026-10-03 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0004_weatheralert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='On file for pension eligibility.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='terra_watch',
            field=models.BooleanField(default=False, help_text='Terra Watch health monitor paired (50 TRX).'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('service', 'Service'), ('tax', 'Tax'), ('pension', 'Pension')], max_length=10),
        ),
        migrations.CreateModel(
            name='CivicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('road', 'Road upgrade'), ('waste', 'Waste management'), ('medical', 'Medical service')], max_length=10)),
                ('sector', models.CharField(choices=[('aurelia', 'Aurelia Basin'), ('vermilion', 'Vermilion Steps'), ('glasslands', 'The Glass Tundra'), ('pelagos', 'Pelagos Deep')], max_length=20)),
                ('location', models.CharField(max_length=140)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civic_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('amount_trx', models.DecimalField(decimal_places=6, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='unique_tax_bill_per_period')],
            },
        ),
    ]
