# Generated by Django 6.1.1 on 2026-10-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0005_profile_date_of_birth_profile_terra_watch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('service', 'Service'), ('tax', 'Tax'), ('pension', 'Pension'), ('fare', 'Fare'), ('bonus', 'Bonus')], max_length=10),
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('elder', 'Elder')], default='self', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FareTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=8)),
                ('route_name', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=8)),
                ('destination', models.CharField(max_length=80)),
                ('departure', models.DateTimeField()),
                ('fare_trx', models.DecimalField(decimal_places=6, max_digits=12)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='terra.traveler')),
            ],
            options={
                'ordering': ['-departure'],
            },
        ),
    ]
