# Generated by Django 6.1.1 on 2026-10-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0009_backfill_welcome_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(choices=[('expedition', 'Expedition'), ('weather', 'Weather'), ('market', 'Market'), ('transport', 'Transport'), ('civic', 'Civic'), ('health', 'Health'), ('science', 'Science')], default='expedition', max_length=12)),
                ('summary', models.CharField(help_text='One-line standfirst shown on the news cards.', max_length=300)),
                ('body', models.TextField(help_text='Article body; blank lines separate paragraphs.')),
                ('source', models.CharField(default='Terra Nova Newsroom', help_text='Byline or wire service shown on the article.', max_length=80)),
                ('is_featured', models.BooleanField(default=False, help_text='Promoted to the lead story on the News page.')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
