# Generated by Django 6.1.1 on 2026-10-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutorial_seen',
            field=models.BooleanField(default=False, help_text='Passenger has finished the first-login Mission Control tour.'),
        ),
    ]
